# Create a LangGraph application that takes a question from the user and uses an OpenAI LLM to generate the answer.

# For example, if the user enters: "Explain APIs to a beginner."

# The application should:

# Take the user's question from the State.
# Send the question to the OpenAI LLM.
# Get the answer generated by the LLM.
# Store the generated answer in state["answer"].
# Display the final answer.

# write the code using langraph

from typing_extensions import TypedDict

from langgraph.graph import StateGraph, START, END
from langchain_openai import ChatOpenAI

from dotenv import load_dotenv


load_dotenv()


class State(TypedDict):
    question: str
    answer: str


llm = ChatOpenAI(model="gpt-4o-mini")


def generate_answer(state: State):
    response = llm.invoke(state["question"])

    return {
        "answer": response.content
    }


graph = StateGraph(State)

graph.add_node("generate_answer", generate_answer)

graph.add_edge(START, "generate_answer")
graph.add_edge("generate_answer", END)

app = graph.compile()


question = input("Enter your question: ")

result = app.invoke({
    "question": question,
    "answer": ""
})


print("\nAnswer:")
print(result["answer"])